# Site settings
title: StackExpert
email: ak@stackexpert.com
description: ""
baseurl: ""
url: "http://stackexpert.com"
twitter_username: ashwinkumar_k
github_username:  ashking
# facebook_username:  IronSummitMedia

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["node_modules"]
